ref(installer): update intaller main script install to conform with new dotfiles structure and requirements

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,14 +1,13 @@
 #!/usr/bin/env bash
 
 set -Eeuo pipefail
+trap cleanup SIGINT SIGTERM ERR EXIT
 
 script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)
 
-packages_to_stow="shell:git:nvim:tmux"
-
 usage() {
   cat <<EOF
-Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-up|--update-upgrade] [-ext|--external-packages-script] [-apt|--apt-packages-list] [-snap|--snap-packages-list]
+Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [--host]
 
 Dotfiles installer script.
 
@@ -16,12 +15,21 @@ Available options:
 
 -h, --help                          Print this help and exit
 -v, --verbose                       Print script debug infor
--up, --update-upgrade		    Update and upgrade system packages
--ext, --external-packages-script    Install external packages using script ${script_dir}/installer/install-external-packages
--apt, --apt-packages-list           Install packages listed in ${script_dir}/installer/apt-packages-list.txt using apt package manager
--snap, --snap-packages-list         Install packages liston in ${script_dir}/installer/snap-packages-list.txt using snap package manager 
+--host                              Flag to enable dotfiles installation for host environment; default installation for container environment
 EOF
   exit
+}
+
+run_cmd() {
+  if [ "${VERBOSE:-0}" -eq 1 ]; then
+    "${@}" || sudo "${@}"
+  else
+    "${@}" 2>/dev/null || sudo "${@}" 2>/dev/null
+  fi
+}
+
+safe_rm() {
+  rm -rf "${1}" 2>/dev/null || sudo rm -rf "${1}" 2>/dev/null || log "WARN" "Failed to remove ${1}"
 }
 
 cleanup() {
@@ -63,47 +71,24 @@ die() {
 }
 
 parse_params() {
-  update_upgrade=0
-  install_external_packages=0
-  install_apt_packages=0
-  install_snap_packages=0
+  VERBOSE=0
+  HOST=0
 
   while :; do
     case "${1-}" in
     -h | --help) usage ;;
-    -v | --verbose) set -x ;;
+    -v | --verbose)
+      VERBOSE=1
+      ;;
     --no-color) NO_COLOR=1 ;;
-    -up | --update-upgrade) update_upgrade=1 ;;
-    -ext | --external-packages-script) install_external_packages=1 ;;
-    -snap | --snap-packages-list) install_snap_packages=1 ;;
-    -apt | --apt-packages-list) install_apt_packages=1 ;;
+    --host)
+      HOST=1
+      ;;
     -?*) die "Unknown option: ${1}" ;;
     *) break ;;
     esac
     shift
   done
-
-  log "Starting up..."
-
-  if [ ${install_external_packages} -eq 0 ] && [ ${install_apt_packages} -eq 0 ] && [ ${install_snap_packages} -eq 0 ]; then
-    log "WARN" "Script running as 'symlinks' farm manager only"
-    log "WARN" "It will fail if required package is not installed"
-    log "WARN" "Please, see ./install --help for usage information"
-  fi
-
-  if [ ${install_apt_packages} -eq 1 ] && [ ! -f "${script_dir}"/installer/apt-packages-list.txt ]; then
-    die "File ${script_dir}/installer/apt-packages-list.txt not found in script directory"
-  fi
-
-  if [ ${install_snap_packages} -eq 1 ] && [ ! -f "${script_dir}"/installer/snap-packages-list.txt ]; then
-    die "File ${script_dir}/installer/snap-pakcages-list.txt not found in script directory"
-  fi
-
-  if [ ${install_external_packages} -eq 1 ] && [ ! -f "${script_dir}"/installer/install-external-packages ]; then
-    die "File 'external-packages' not found in script directory"
-  fi
-
-  log "Parameters parsed successfully"
 
   return 0
 }
@@ -111,61 +96,42 @@ parse_params() {
 parse_params "${@}"
 setup_colors
 
-iterate_array() {
-  local array="${1}"
+set -- # This clears any leftover arguments before running scripts
 
-  IFS=':' read -ra array <<<"${array}"
-  for item in "${array[@]}"; do
-    echo "${item}"
-  done
-}
+log "Updating system..."
+sudo apt-get update
+log "Update completed"
 
-install_external_packages() {
-  log "Installing external packages using script"
-  bash "${script_dir}/installer/install-external-packages"
-  log "SUCCESS" "External packages installation complete"
-}
-
-capslock_ctrl_mapping() {
-  log "Mapping CapsLock key to Ctrl..."
-  gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
-  log "Key mapping complete"
-}
-
-install_tmux_plugin_manager() {
-  git clone https://github.com/tmux-plugins/tpm "${HOME}"/.tmux/plugins/tpm
-}
-
-if command -v gnome-terminal; then
-  capslock_ctrl_mapping
+if [ "${HOST}" -eq 1 ]; then
+  log "Starting installation for host environment"
+  bash "${script_dir}/bin/install_apt_packages.sh"
+  bash "${script_dir}/bin/install_snap_packages.sh"
+  bash "${script_dir}/bin/install_docker_engine.sh"
+  bash "${script_dir}/bin/install_github_cli.sh"
+  bash "${script_dir}/bin/install_nerd_fonts.sh"
+  bash "${script_dir}/bin/install_neovim.sh"
+  bash "${script_dir}/bin/install_starship.sh"
+  bash "${script_dir}/bin/install_tpm.sh"
+  bash "${script_dir}/bin/install_zettelkasten.sh"
+  bash "${script_dir}/bin/capslock_ctrl_map.sh"
+else
+  log "Starting installation for container environment"
+  bash "${script_dir}/bin/install_apt_packages.sh"
+  bash "${script_dir}/bin/install_nerd_fonts.sh"
+  bash "${script_dir}/bin/install_neovim.sh"
+  bash "${script_dir}/bin/install_starship.sh"
+  bash "${script_dir}/bin/install_tpm.sh"
+  bash "${script_dir}/bin/install_zettelkasten.sh"
 fi
 
-if [ ${update_upgrade} -eq 1 ]; then
-  log "Updating system..."
-  sudo apt-get update
-  log "Update completed"
+packages_to_stow="shell:git:nvim:tmux"
 
-  log "Upgrading system"
-  sudo apt-get upgrade -y
-  log "System upgrade completed"
-fi
-
-if [ ${install_apt_packages} -eq 1 ]; then . bin/install_apt_packages.sh; fi
-if [ ${install_snap_packages} -eq 1 ]; then . bin/install_snap_packages.sh; fi
-if [ ${install_external_packages} -eq 1 ]; then install_external_packages; fi
-
-log "Setting up symlinks with stow..."
-for package in $(iterate_array ${packages_to_stow}); do
-  stow -R --no-folding --verbose=2 --target="${HOME}" "${package}"
+log "Farming symlinks with stow..."
+IFS=':' read -ra packages <<<"${packages_to_stow}"
+for package in "${packages[@]}"; do
+  run_cmd stow -R --no-folding --verbose=2 --target="${HOME}" "${package}"
 done
 
-log "Sourcing .profile file to activate environment"
-. "${HOME}"/.profile
+log "SUCCESS" "Dotfiles installation complete"
 
-if [ ! -d "${HOME}"/.tmux/plugins/tpm ]; then install_tmux_plugin_manager; fi
-
-gnome_system_theme_switch_cron
-
-log "SUCCESS" "Dotfiles and packages installation complete"
-
-exec "${SHELL}"
+exec "${SHELL}" -l
